#!/usr/bin/env bash
# clean temporary files and binaries, without touching other files or log

SCRIPTS_DIR="$(dirname $(realpath -P $0))/"
. "${SCRIPTS_DIR}CPX-common.sh"
CPX_WORK_DIR=$(heal_DIR CPX_WORK_DIR)
 WORK_DIR="${CPX_WORK_DIR:-/tmp/cpx/}"
  cd $WORK_DIR

CPX_files=$(ls -1f *.cpp *.x *.s *.o *.ii *.ii~ *.ii.orig *temp* *.unchanged.hpp *.cpp.prehash *.cpp.prehash.errors *.cpp.prehash.transformed \ 
*.cpp.prehash.transformed.errors *.cpp.errors *[0-9,a-z].hash *[0-9,a-z].inc| grep '^CPX-')
if test -z "$CPX_files"
then echo "Nothing to clean"
else rm -v $CPX_files
fi


# expect that only the log files remains, show that this is correct.
# note that these files are delibarately are not deleted to ensure
# operations are handled correctly and it is jet to be decided how 
# to handle those files. If deletion is the proper way, add the
# required pattern to the CPX_files list above.
CPX_remaining=$(ls CPX-* | grep -Ev 'CPX-runner(-[0-9]+)?\.log')
if test -n "$CPX_remaining"
then 
    echo -e "${HYELLOW}Warning: It seems that following files remain"
    echo -e "---------------------------------------------"
    echo -e "'$CPX_remaining'"
    echo -e "---------------------------------------------"
    echo -e "${NOCOLOR}"
fi
cd - > /dev/null

