#!/usr/bin/env bash
# Show error log and locate at the begin of last compilation error.

SCRIPTS_DIR="$(dirname $(realpath -P $0))/"
. "${SCRIPTS_DIR}CPX-common.sh"
CPX_WORK_DIR=$(heal_DIR CPX_WORK_DIR)

WORK_DIR="${CPX_WORK_DIR:-/tmp/cpx/}"

cd "$WORK_DIR"

while :
ls -1rt *.sourcelines
  lastSourceLines=$(ls -1rt *.sourcelines| tail -1)
  do less '+>' -R "$lastSourceLines"
done

