#!/usr/bin/env bash
# Show error log and locate at the begin of last compilation error.

SCRIPTS_DIR="$(dirname $(realpath -P $0))/"
. "${SCRIPTS_DIR}CPX-common.sh"
CPX_WORK_DIR=$(heal_DIR CPX_WORK_DIR)

WORK_DIR="${CPX_WORK_DIR:-/tmp/cpx/}"
if [ ! -f ${WORK_DIR}/CPX-runner.log ]
then
    # make following 'less' wait
    echo "" > ${WORK_DIR}/CPX-runner.log
fi
while :
  do less -R '+?\-\-\-\[.*\]\-\-\-|\ Transforming' $(ls -1t ${WORK_DIR}/CPX-runner*.log)
done

